<main class="px-2 mx-auto max-w-3xl my-20">
  <div class="px-2">
    <h1 class="text-4xl font-semibold tracking-tight">
      colophon.
      <div class="w-24 h-1.5 rounded-lg bg-muted-foreground mt-1" />
    </h1>
    <div class="space-y-4 mt-8">
      <p class="leading-loose text-lg">
        This site is built with the <a href="https://kit.svelte.dev/" class="link">SvelteKit</a>
        full stack framework, itself a meta-framework of the
        <a class="link" href="https://svelte.dev/">Svelte</a> web framework. The body font is
        <a href="https://vercel.com/font" class="link">Vercel's Geist Sans</a>
        and <a href="https://fonts.google.com/specimen/Merriweather" class="link">Merriweather</a> in
        select parts.
      </p>
      <p class="leading-loose text-lg">
        My <a class="link" href="https://blog.youwen.dev">blog</a> is generated by a static site
        generator library called <a href="https://jaspervdj.be/hakyll/" class="link">Hakyll</a>,
        which is configured with the Haskell programming language (you could consider it a Haskell
        eDSL for configuring static sites). The web portions are raw HTML created by hand. I
        leverage the Haskell library
        <a class="link" href="https://pandoc.org/">Pandoc</a> to convert Markdown files into HTML
        for each blog post. It gets perfect 100s across the board on Google's lighthouse test. The
        serif font is
        <a href="https://fonts.google.com/specimen/Merriweather" class="link">Merriweather</a>
        and the sans-serif font is
        <a href="https://fonts.google.com/specimen/Open+Sans" class="link">Open Sans</a>.
      </p>
      <p class="leading-loose text-lg">
        The CSS on both sites is done with <a class="link" href="https://tailwindcss.com/"
          >TailwindCSS</a
        >. Tailwind is a terrible, ugly way to do CSS; however, every other method of doing CSS is
        arguably worse.
      </p>
    </div>
  </div>
</main>
